<a href="https://colab.research.google.com/github/iSanoussi/Deep-Learning-TensorFlow/blob/main/Copie_de_stress_test_sort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.random.randint(0,10, 20)

In [ ]:
print(A)
print(sorted(A))

[6 2 6 9 2 7 6 7 2 3 5 1 0 1 5 6 3 0 9 9]
[0, 0, 1, 1, 2, 2, 2, 3, 3, 5, 5, 6, 6, 6, 6, 7, 7, 9, 9, 9]


In [ ]:
def my_sort(B):
  A = B.copy()
  n = len(A)


  for i in range(n):
    minim = A[i]
    ind = i
    for j in range(i,n):
      if A[j] < minim :
        ind  = j
        minim = A[j]
    A[i], A[ind] = A[ind], A[i]
  return A



In [ ]:
my_sort(A)

array([0, 0, 1, 1, 2, 2, 2, 3, 3, 5, 5, 6, 6, 6, 6, 7, 7, 9, 9, 9])

In [ ]:
A

array([0, 1, 1, 1, 2, 2, 4, 4, 4, 4, 5, 5, 6, 7, 8, 8, 9, 9, 9, 9])

# Objectif : rediger un stress test
- générer une boucle while() (infinie)
- générer une liste aléatoire
- comparer sorted(liste) et my_sort(liste)
- renvoyer un message d'erreur si le résultat est différent
- continuer si résultat est identique (attention aux types de liste)
- éventuellement ajouter un compteur de cas corrects